### ISSUE TITLE
How generate the ENCRYPTION_KEY?

### ISSUE THREAD

**Issue by ArthurPedroti** [Edwin-Luijten/strapi-encryptable-field#17]
How can I generate the ENCRYPTION_KEY?

I'm trying different string but I got the same "Invalid key length" error all time

**Comment by BayBreezy** [comment]
Run this command `node -e "console.log(require('crypto').randomBytes(16).toString('hex'));"`

It really needs to be added to the docs.

**Comment by ArthurPedroti** [comment]
On the strapi docs page, it says that the key has 32 bytes, and the code you write generates a hex string of 16 bytes.

It's right?

![image](https://github.com/Edwin-Luijten/strapi-encryptable-field/assets/52859409/a3643d9f-9b46-45e0-887d-1b60f7113736)

**Comment by BayBreezy** [comment]
Yeah.... about that.. I just went the the value under the IV Length column and that works. 

The strapi docs don't seem to pull in the updated readme's automatically
